Workers:
  replicaCount: 3
  image: "yethitech/performance-testing:3-2-25"
  heap: "-Xms1g -Xmx4g"
  persistence:
    size: "5Gi"
    storageClassName: "efs-sc"
    subPath: backend/tenjinpt-workers

Master:
  image: "yethitech/performance-testing:kube-3-2-25"
  heap: "-Xms1g -Xmx4g"

  resources:
    requests:
      memory: "5Gi"
      cpu: "1"
    limits:
      memory: "5Gi"
      cpu: "3"

  service:
    type: ClusterIP

  persistence:
    size: "6Gi"
    storageClassName: "efs-sc"
    subPath: backend/tenjinpt-prod-master-pv

Grafana:
  username: admin
  password: admin123
  service:
    type: NodePort
    port: 3000
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: standard

InfluxDB:
  image: "influxdb:2.7.11"
  username: "admin"
  password: "Admin@123"
  org: "jmeter"
  bucket: "jmeter"
  token: "YOUR_INFLUXDB_TOKEN_HERE"
  retention: "30d"
  persistence:
    size: "30Gi"
    storageClassName: "standard"
  service:
    type: NodePort

jmeterVts:
  service:
    type: NodePort