apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - pt-influx.yethi.in
    - pt-vts.yethi.in
    secretName: tenjin-tls

  rules:
  - host: pt-influx.yethi.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-influxdb
            port:
              number: 8086

  - host: pt-vts.yethi.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-tenjin-pulse-vts
            port:
              number: 8080