apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-tenjin-pulse-worker
  labels:
    app: {{ .Release.Name }}-tenjin-pulse-worker

spec:
  serviceName: {{ .Release.Name }}-tenjin-pulse-worker
  replicas: {{ .Values.Workers.replicaCount | default 3 }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-tenjin-pulse-worker

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tenjin-pulse-worker

    spec:
      containers:
        - name: tenjin-pulse-worker
          image: {{ .Values.Workers.image }}

          env:
            - name: HEAP
              value: {{ .Values.Workers.heap }}

          ports:
            - containerPort: 1099
            - containerPort: 60000
            - containerPort: 60001

          volumeMounts:
            - name: worker-data
              mountPath: /csv

          command:
            - /bin/sh
            - -c

          args:
            - |
              set -x
              echo "Starting JMeter Worker $HOSTNAME"

              jmeter -s \
                -Dserver.rmi.ssl.disable=true \
                -Dserver_port=1099 \
                -Dserver.rmi.localport=60000 \
                -Dclient.rmi.localport=60001

  volumeClaimTemplates:
    - metadata:
        name: worker-data
        labels:
          app: {{ .Release.Name }}-tenjin-pulse-worker

      spec:
        accessModes:
          - ReadWriteMany

        storageClassName: {{ .Values.Workers.persistence.storageClassName | default "efs-sc" }}

        resources:
          requests:
            storage: {{ .Values.Workers.persistence.size | default "5Gi" }}